# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23f7f6978f9dd3af0f6a9c08b49318dd225212628cab94a48eb1018c318048bf1e6bf23705e61659dda32695dfa6b4442f40dfd2aa877ef12fb92aaedd2a1b28

test:
  secret_key_base: 16e3833cdf51d4362abdbbbe796ce086feb1ad90dac106abe3c57fa51b89188033aa7613bc41c44ef815564e49a75a3aac544012209f3f017af6381f591fd381

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
